name: address_search_field
description: An address search field which helps to autocomplete an address by a reference. It can be used to get Directions beetwen two points.
version: 5.0.0
homepage: https://github.com/JosLuna98/address_search_field

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  google_maps_flutter: ^2.1.5
  flutter_riverpod: ^1.0.3
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  plugin:
    platforms:
      android:
        package: dev.jostech.address_search_field
        pluginClass: AddressSearchFieldPlugin
      ios:
        pluginClass: AddressSearchFieldPlugin
      windows:
        pluginClass: AddressSearchFieldPlugin
      web:
        pluginClass: AddressSearchFieldWeb
        fileName: address_search_field_web.dart
