name: address_search_field
description: An address search field which helps to autocomplete an address by a reference. It can be used to get Directions beetwen two points.
version: 3.1.0-nullsafety.0
homepage: https://github.com/JosLuna98/address_search_field.git

environment:
  sdk: ">=2.12.0-259.8.beta <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http: ^0.13.0
  google_maps_flutter: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: dev.jostech.address_search_field
        pluginClass: AddressSearchFieldPlugin
      ios:
        pluginClass: AddressSearchFieldPlugin
      windows:
        pluginClass: AddressSearchFieldPlugin
      web:
        pluginClass: AddressSearchFieldWeb
        fileName: address_search_field_web.dart
